In [17]:
import matplotlib.pyplot as plt
import numpy as np

In [23]:
nums_1d = np.ones((3), dtype = np.int8)
nums_1d

array([1, 1, 1], dtype=int8)

In [20]:
nums_2d = np.ones((3, 4), dtype = np.int8)
nums_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [21]:
nums_3d = np.ones((2, 3, 4), dtype = np.int8)
nums_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [26]:
array_nums = np.array([3,4])

In [28]:
array_nums * 2

array([6, 8])

In [34]:
array_nums_more = np.array([10,20])

In [35]:
array_nums * array_nums_more

array([30, 80])

In [36]:
array_nums + array_nums_more

array([13, 24])

In [37]:
array_nums - array_nums_more

array([ -7, -16])

In [38]:
array_nums / array_nums_more

array([0.3, 0.2])

In [49]:
np.ndarray((2,4), np.int8) # garbage data

array([[-48, -15, -82,  17],
       [ 25,  86,   0,   0]], dtype=int8)

In [76]:
from numpy import random
rands = np.random.randn(2,4) * 100 # random

In [79]:
rands.astype('int8')

array([[ 19,  87,  20,  61],
       [112,  41,  48, -31]], dtype=int8)

In [86]:
#np.save("rands.npy", rands)

In [87]:
for i in rands:
    print(i)

[19.80737473 87.58187297 20.03322492 61.97384227]
[112.48870687  41.30751249  48.6753392  -31.97367749]
